"""
MemoryEntry – structured data object for a single memory record.

Each memory captures one complete interaction cycle:
  perception → decision → execution → feedback.

The entry contains:
  - An index vector for fast similarity retrieval
  - Raw scene data (point cloud + features) for precise cross-instance alignment
  - An experience component (preference matrix, reward, action parameters)
  - Metadata (timestamps, category labels, confidence, access statistics)
"""

from __future__ import annotations

import uuid
import time
import json
from dataclasses import dataclass, field, asdict
from typing import Optional, Dict, Any, List

import numpy as np


@dataclass
class MemoryEntry:
    """Structured memory entry for one interaction experience.

    Attributes
    ----------
    id : str
        Unique identifier (UUID4).
    index_vector : np.ndarray
        L2-normalised index vector of shape ``[D]`` (e.g. 128-dim),
        generated by :class:`MemoryIndexer` from the ARM feature.
    point_cloud : np.ndarray
        Historical point-cloud coordinates, shape ``[N_hist, 3]``.
    point_features : np.ndarray
        Per-point feature vectors extracted from IAG backbone,
        shape ``[N_hist, D_feat]``.
    scene_image : Optional[np.ndarray]
        Associated RGB image (optional, for debugging / visualisation).
    preference_matrix : np.ndarray
        Per-point preference values, shape ``[N_hist]``.
        Positive in interaction-success regions, negative in failure
        regions, zero elsewhere.
    reward : float
        Scalar reward for the entire interaction
        (e.g. success +1.0, partial +0.5, failure -1.0).
    action_parameters : Dict[str, Any]
        Executed action parameters (e.g. 6-D grasp pose).
    outcome : str
        Result label: ``"success"``, ``"failure"``, or ``"partial"``.
    timestamp : float
        Unix timestamp when the memory was created.
    object_category : str
        Object category (e.g. ``"Mug"``, ``"Chair"``).
    affordance_label : str
        Interaction / affordance label (e.g. ``"grasp"``, ``"sit"``).
    confidence : float
        Prediction confidence from the model at the time of interaction.
    access_count : int
        How many times this memory has been successfully retrieved and used.
    text_embedding : Optional[np.ndarray]
        Projected text embedding (from IAG_TextEmb), shape ``[text_dim]``.
        Stored so that the memory can be matched more finely by affordance
        semantics in addition to visual similarity.
    """

    # ── Core index & retrieval key ──────────────────────────────────────
    id: str = field(default_factory=lambda: uuid.uuid4().hex)
    index_vector: np.ndarray = field(default_factory=lambda: np.array([]))

    # ── Raw scene data (for precise alignment) ─────────────────────────
    point_cloud: np.ndarray = field(default_factory=lambda: np.array([]))
    point_features: np.ndarray = field(default_factory=lambda: np.array([]))
    scene_image: Optional[np.ndarray] = None

    # ── Experience content ──────────────────────────────────────────────
    preference_matrix: np.ndarray = field(default_factory=lambda: np.array([]))
    reward: float = 0.0
    action_parameters: Dict[str, Any] = field(default_factory=dict)
    outcome: str = "unknown"

    # ── Metadata ────────────────────────────────────────────────────────
    timestamp: float = field(default_factory=time.time)
    object_category: str = ""
    affordance_label: str = ""
    confidence: float = 0.0
    access_count: int = 0

    # ── Optional text embedding (for IAG_TextEmb) ──────────────────────
    text_embedding: Optional[np.ndarray] = None

    # ── Serialisation helpers ───────────────────────────────────────────

    def to_dict(self) -> Dict[str, Any]:
        """将MemoryEntry转换为JSON可序列化的字典。

        NumPy数组被转换为base64编码的字符串，以便在SQLite BLOB列中紧凑存储。

        返回:
            Dict[str, Any]: 包含所有MemoryEntry字段的字典，NumPy数组以base64字符串形式存储
        """
        import base64

        def _encode(arr: Optional[np.ndarray]) -> Optional[str]:
            """将NumPy数组编码为base64字符串。

            参数:
                arr: Optional[np.ndarray] - 要编码的NumPy数组

            返回:
                Optional[str] - base64编码的字符串，如果输入为None则返回None
            """
            if arr is None:
                return None
            return base64.b64encode(arr.astype(np.float32).tobytes()).decode("ascii")

        return {
            "id": self.id,
            "index_vector": _encode(self.index_vector),
            "point_cloud": _encode(self.point_cloud),
            "point_features": _encode(self.point_features),
            "scene_image": _encode(self.scene_image),
            "preference_matrix": _encode(self.preference_matrix),
            "reward": self.reward,
            "action_parameters": json.dumps(self.action_parameters),
            "outcome": self.outcome,
            "timestamp": self.timestamp,
            "object_category": self.object_category,
            "affordance_label": self.affordance_label,
            "confidence": self.confidence,
            "access_count": self.access_count,
            "text_embedding": _encode(self.text_embedding),
        }

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "MemoryEntry":
        """从序列化的字典重建MemoryEntry实例。

        参数:
            d: Dict[str, Any] - 包含MemoryEntry字段的字典，NumPy数组以base64字符串形式存储

        返回:
            MemoryEntry: 重建的MemoryEntry实例
        """
        import base64

        def _decode(s: Optional[str], shape_hint: Optional[List[int]] = None) -> Optional[np.ndarray]:
            """将base64字符串解码为NumPy数组。

            参数:
                s: Optional[str] - base64编码的字符串
                shape_hint: Optional[List[int]] - 数组形状提示

            返回:
                Optional[np.ndarray] - 解码后的NumPy数组，如果输入为None则返回None
            """
            if s is None:
                return None
            raw = base64.b64decode(s.encode("ascii"))
            arr = np.frombuffer(raw, dtype=np.float32)
            if shape_hint is not None:
                try:
                    arr = arr.reshape(shape_hint)
                except ValueError:
                    pass  # leave flat if shape mismatch
            return arr

        return cls(
            id=d["id"],
            index_vector=_decode(d.get("index_vector")) or np.array([]),
            point_cloud=_decode(d.get("point_cloud")) or np.array([]),
            point_features=_decode(d.get("point_features")) or np.array([]),
            scene_image=_decode(d.get("scene_image")),
            preference_matrix=_decode(d.get("preference_matrix")) or np.array([]),
            reward=float(d.get("reward", 0.0)),
            action_parameters=json.loads(d.get("action_parameters", "{}")),
            outcome=d.get("outcome", "unknown"),
            timestamp=float(d.get("timestamp", 0.0)),
            object_category=d.get("object_category", ""),
            affordance_label=d.get("affordance_label", ""),
            confidence=float(d.get("confidence", 0.0)),
            access_count=int(d.get("access_count", 0)),
            text_embedding=_decode(d.get("text_embedding")),
        )

    def get_index_vector_shape(self) -> Optional[List[int]]:
        """返回索引向量的形状，如果为空则返回None。

        返回:
            Optional[List[int]]: 索引向量的形状列表，如[128]，或None如果向量为空
        """
        if self.index_vector.size == 0:
            return None
        return list(self.index_vector.shape)

    def get_point_cloud_shape(self) -> Optional[List[int]]:
        """返回点云的形状，如果为空则返回None。

        返回:
            Optional[List[int]]: 点云的形状列表，如[N_hist, 3]，或None如果点云为空
        """
        if self.point_cloud.size == 0:
            return None
        return list(self.point_cloud.shape)

    def get_point_features_shape(self) -> Optional[List[int]]:
        """返回点特征的形状，如果为空则返回None。

        返回:
            Optional[List[int]]: 点特征的形状列表，如[N_hist, D_feat]，或None如果特征为空
        """
        if self.point_features.size == 0:
            return None
        return list(self.point_features.shape)

    def summary(self) -> str:
        """生成人类可读的一行摘要字符串。

        返回:
            str: 包含关键信息的摘要字符串，格式为"MemoryEntry(id=..., affordance=..., ...)"
        """
        return (
            f"MemoryEntry(id={self.id[:8]}..., "
            f"affordance={self.affordance_label}, "
            f"object={self.object_category}, "
            f"outcome={self.outcome}, "
            f"reward={self.reward:.1f}, "
            f"conf={self.confidence:.2f}, "
            f"access={self.access_count})"
        )